project_id = "gaxmjxiqjirjeyemjcyc"

[functions.analyze-story]
verify_jwt = false

[functions.generate-character-reference]
verify_jwt = false

[functions.edit-scene-image]
verify_jwt = false

[functions.upload-reference-image]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.api-admin]
verify_jwt = false
